const DB_KEY='tss_talent_buddy_v1';
const defaultData={requirements:[{id:'TSS001',client:'IntelMacc',title:'Senior Service Manager',location:'Mumbai',experience:'7+ years',industry:'Engineering',status:'Active',skills:['Service Management','Customer Handling','Team Leadership','Escalation Management','CRM'],preferred:['Industrial Automation','Sales Coordination'],qualification:'Engineering / MBA preferred',responsibilities:'Manage service operations, customer escalations, team performance and service delivery.',jdText:'',aiSuggested:false},{id:'TSS002',client:'Neosoft Technologies',title:'ASP.NET Core + Angular Developer',location:'Delhi',experience:'5+ years',industry:'IT',status:'Active',skills:['ASP.NET Core','C#','Angular','REST API','SQL Server'],preferred:['Azure','Git','Entity Framework'],qualification:'B.E./B.Tech/MCA',responsibilities:'Develop enterprise web applications using .NET Core and Angular.',jdText:'',aiSuggested:false},{id:'TSS003',client:'Neosoft Technologies',title:'Database Developer',location:'Delhi',experience:'5+ years',industry:'IT',status:'Active',skills:['MS SQL','MySQL','Stored Procedures','Query Optimization','Database Design'],preferred:['ETL','Performance Tuning'],qualification:'Graduate in CS/IT',responsibilities:'Design, optimize and maintain relational databases.',jdText:'',aiSuggested:false}],candidates:[],screenings:[],activity:[]};
let db=loadDB();
function loadDB(){try{return {...defaultData,...JSON.parse(localStorage.getItem(DB_KEY)||'{}')}}catch(e){return structuredClone(defaultData)}}
function saveDB(){localStorage.setItem(DB_KEY,JSON.stringify(db));renderAll()}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function norm(v=''){return String(v).toLowerCase().replace(/[^a-z0-9+#. ]/g,' ')}
function tokens(v=''){return [...new Set(norm(v).split(/\s+/).filter(x=>x.length>2))]}
function splitSkills(v=''){return [...new Set(String(v).split(/[,;\n|]/).map(x=>x.trim()).filter(Boolean))]}
function esc(v=''){return String(v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function activeReqs(){return db.requirements.filter(r=>r.status==='Active')}
function screeningLabel(score){return score>=75?'Strong Match':score>=50?'Review Recommended':'Not Suitable'}
function statusBadge(label){const cls=label==='Strong Match'?'green':label==='Review Recommended'?'amber':label==='Not Suitable'?'red':'blue';return `<span class="badge ${cls}">${label}</span>`}
function gotoView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const titles={dashboard:'Recruitment Dashboard',requirements:'Job Profiles & JD Intelligence',screening:'New Resume Screening',candidates:'Candidate CV Library',history:'Candidate History'};document.getElementById('pageTitle').textContent=titles[id]||'Talent Buddy'}
document.getElementById('nav').addEventListener('click',e=>{if(e.target.dataset.view)gotoView(e.target.dataset.view)});document.querySelectorAll('[data-open-screening]').forEach(b=>b.onclick=()=>gotoView('screening'));
function calculateExistingMatches(){let n=0;activeReqs().forEach(r=>db.candidates.forEach(c=>{if(scoreCandidate(c.resumeText||'',r,c).score>=55)n++}));return n}
function renderDashboard(){const active=activeReqs(),clients=new Set(active.map(r=>r.client)).size,strong=db.screenings.filter(s=>s.recommendation==='Strong Match').length,review=db.screenings.filter(s=>s.recommendation==='Review Recommended').length,week=Date.now()-7*864e5,newCV=db.candidates.filter(c=>new Date(c.uploadDate).getTime()>week).length,ai=active.filter(r=>r.aiSuggested).length;const stats=[['Active Clients',clients],['Active Requirements',active.length],['Stored Candidates',db.candidates.length],['New CVs This Week',newCV],['Strong Matches',strong],['Needs Review',review],['Existing CV Matches',calculateExistingMatches()],['AI Suggested Skills',ai]];statGrid.innerHTML=stats.map(([a,b])=>`<div class="stat-card"><span>${a}</span><strong>${b}</strong></div>`).join('');const grouped={};active.forEach(r=>(grouped[r.client]??=[]).push(r));requirementsByClient.innerHTML=Object.entries(grouped).map(([c,rs])=>`<div class="client-row"><div><strong>${esc(c)}</strong><small style="display:block;color:var(--muted)">${rs.map(r=>esc(r.title)).join(' • ')}</small></div><span class="badge blue">${rs.length} Active</span></div>`).join('')||'<div class="empty-state">No active requirements</div>';const total=Math.max(db.screenings.length,1),dist=[['Strong Match',strong],['Review Recommended',review],['Not Suitable',db.screenings.filter(s=>s.recommendation==='Not Suitable').length]];matchDistribution.innerHTML=dist.map(([l,n])=>`<div class="bar-row"><div class="bar-label"><span>${l}</span><strong>${n}</strong></div><div class="bar"><i style="width:${Math.round(n/total*100)}%"></i></div></div>`).join('');recentActivity.innerHTML=(db.activity.slice(-6).reverse().map(a=>`<div class="activity-row"><div><strong>${esc(a.title)}</strong><small style="display:block;color:var(--muted)">${esc(a.detail)}</small></div><small>${new Date(a.date).toLocaleDateString()}</small></div>`).join('')||'<div class="empty-state">No activity yet</div>');const incomplete=active.filter(r=>!r.skills?.length||!r.responsibilities).length;alerts.innerHTML=`<div class="alert-row"><span>Requirements without complete JD</span><span class="badge ${incomplete?'amber':'green'}">${incomplete}</span></div><div class="alert-row"><span>Candidates requiring review</span><span class="badge ${review?'amber':'green'}">${review}</span></div><div class="alert-row"><span>Existing CV matches found</span><span class="badge blue">${calculateExistingMatches()}</span></div>`}
function renderSidebar(){const grouped={};activeReqs().forEach(r=>(grouped[r.client]??=[]).push(r));activeRequirementMini.innerHTML=Object.entries(grouped).map(([c,rs])=>`<div class="mini-client"><strong>${esc(c)} · ${rs.length}</strong><small>${rs.map(r=>esc(r.title)).join(', ')}</small></div>`).join('')}
function renderRequirements(){requirementCards.innerHTML=db.requirements.map(r=>`<article class="req-card"><span class="eyebrow">${esc(r.id)} · ${esc(r.client)}</span><h4>${esc(r.title)}</h4><div class="req-meta"><span>${esc(r.location||'Location not set')}</span><span>•</span><span>${esc(r.experience||'Experience not set')}</span><span>•</span>${statusBadge(r.status)}</div><div class="skill-cloud">${(r.skills||[]).map(s=>`<span class="skill ${r.aiSuggested?'ai':''}">${esc(s)}${r.aiSuggested?' · AI':''}</span>`).join('')}</div><small style="color:var(--muted)">${esc(r.responsibilities||'Responsibilities not added')}</small><div class="card-actions"><button class="btn ghost edit-req" data-id="${r.id}">Edit JD</button><button class="btn primary screen-req" data-id="${r.id}">Screen Candidate</button></div></article>`).join('');document.querySelectorAll('.edit-req').forEach(b=>b.onclick=()=>openRequirement(b.dataset.id));document.querySelectorAll('.screen-req').forEach(b=>b.onclick=()=>{screenRequirement.value=b.dataset.id;updateSelectedRequirement();gotoView('screening')})}
function populateScreenReq(){const val=screenRequirement.value;screenRequirement.innerHTML=activeReqs().map(r=>`<option value="${r.id}">${r.id} — ${esc(r.client)} — ${esc(r.title)}</option>`).join('');if(val&&activeReqs().some(r=>r.id===val))screenRequirement.value=val;updateSelectedRequirement()}
function updateSelectedRequirement(){const r=db.requirements.find(x=>x.id===screenRequirement.value);selectedRequirementSummary.innerHTML=r?`<strong>${esc(r.title)}</strong><br><small>${esc(r.client)} · ${esc(r.location)} · ${esc(r.experience)}</small><div class="skill-cloud">${(r.skills||[]).map(s=>`<span class="skill">${esc(s)}</span>`).join('')}</div>`:'No active requirement selected'}screenRequirement.onchange=updateSelectedRequirement;
function renderCandidates(filter=''){const q=norm(filter),rows=db.candidates.filter(c=>!q||norm(`${c.name} ${c.email} ${c.phone} ${c.designation} ${c.location}`).includes(q));candidateTableWrap.innerHTML=rows.length?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Candidate</th><th>Experience</th><th>Location</th><th>Notice</th><th>Last Screened</th><th>Status</th></tr></thead><tbody>${rows.map(c=>{const last=db.screenings.filter(s=>s.candidateId===c.id).at(-1);return `<tr><td><strong>${esc(c.name)}</strong><br><small>${esc(c.email)} · ${esc(c.phone)}</small><br><small>${esc(c.designation||'')}</small></td><td>${esc(c.totalExperience||'-')} yrs</td><td>${esc(c.location||'-')}</td><td>${esc(c.noticePeriod||'-')}</td><td>${esc(c.lastScreenedDate?new Date(c.lastScreenedDate).toLocaleDateString():'Never')}</td><td>${last?statusBadge(last.recommendation):'<span class="badge blue">Stored</span>'}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty-state">No candidates stored yet</div>'}
candidateSearch.oninput=e=>renderCandidates(e.target.value);
function renderHistory(){historyWrap.innerHTML=db.screenings.length?`<div style="overflow:auto"><table class="data-table"><thead><tr><th>Date</th><th>Candidate</th><th>Requirement</th><th>Score</th><th>Recommendation</th><th>Recruiter Decision</th><th>Notes</th></tr></thead><tbody>${db.screenings.slice().reverse().map(s=>{const c=db.candidates.find(x=>x.id===s.candidateId),r=db.requirements.find(x=>x.id===s.requirementId);return `<tr><td>${new Date(s.date).toLocaleString()}</td><td><strong>${esc(c?.name||'Unknown')}</strong></td><td>${esc(r?.client||'')}<br><small>${esc(r?.title||'')}</small></td><td><strong>${s.score}/100</strong></td><td>${statusBadge(s.recommendation)}</td><td>${esc(s.recruiterDecision||'Pending')}</td><td>${esc(s.notes||'-')}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty-state">No screening history yet</div>'}
function renderAll(){renderDashboard();renderSidebar();renderRequirements();populateScreenReq();renderCandidates(candidateSearch?.value||'');renderHistory()}
function roleSkillSuggestions(title,industry){const t=norm(title+' '+industry);const maps=[[/\.net|angular|developer|software/,['C#','ASP.NET Core','REST API','SQL','Git','Unit Testing','Debugging','Agile']],[/database|sql/,['SQL Server','MySQL','Stored Procedures','Query Optimization','Database Design','Indexing','Performance Tuning','ETL']],[/sales|business development|bdm/,['B2B Sales','Lead Generation','Client Acquisition','Negotiation','CRM','Pipeline Management','Revenue Targeting','Stakeholder Management']],[/manager|service/,['Team Leadership','Service Management','Customer Handling','Escalation Management','SLA Management','MIS Reporting','Process Improvement','Stakeholder Management']],[/data engineer/,['Python','SQL','ETL','Data Warehousing','Spark','Cloud','Airflow','Data Modeling']]];for(const [re,skills] of maps)if(re.test(t))return skills;return ['Communication','Stakeholder Management','Problem Solving','Domain Knowledge','Reporting','Process Management','Team Collaboration','Analytical Skills']}
function parseJDText(txt){const lower=txt.toLowerCase(),loc=(txt.match(/(?:location|based at|work location)[:\- ]+([^\n,]+)/i)||[])[1]||'',exp=(txt.match(/(\d+\+?\s*(?:-|to)?\s*\d*\s*years?)/i)||[])[1]||'',qual=(txt.match(/(?:qualification|education)[:\- ]+([^\n]+)/i)||[])[1]||'';const common=['Java','Spring Boot','Angular','React','Node.js','Python','SQL','MySQL','MS SQL','AWS','Azure','Docker','Kubernetes','C#','ASP.NET Core','REST API','CRM','B2B Sales','Team Leadership','Service Management','Power BI','Tableau','Excel'];const skills=common.filter(s=>lower.includes(s.toLowerCase()));return {location:loc.trim(),experience:exp.trim(),qualification:qual.trim(),skills}}
const dlg=document.getElementById('requirementDialog');addRequirementBtn.onclick=()=>openRequirement();function openRequirement(id){requirementForm.reset();reqId.value='';suggestedSkills.innerHTML='';const r=id?db.requirements.find(x=>x.id===id):null;if(r){reqId.value=r.id;reqClient.value=r.client;reqTitle.value=r.title;reqLocation.value=r.location||'';reqExperience.value=r.experience||'';reqIndustry.value=r.industry||'';reqStatus.value=r.status||'Active';reqJdText.value=r.jdText||'';reqSkills.value=(r.skills||[]).join(', ');reqPreferred.value=(r.preferred||[]).join(', ');reqQualification.value=r.qualification||'';reqResponsibilities.value=r.responsibilities||''}dlg.showModal()}
generateSkillsBtn.onclick=()=>{const s=roleSkillSuggestions(reqTitle.value,reqIndustry.value);suggestedSkills.innerHTML=s.map(x=>`<button type="button" class="skill ai suggest-chip" data-skill="${esc(x)}">${esc(x)} · AI Suggested</button>`).join('');document.querySelectorAll('.suggest-chip').forEach(b=>b.onclick=()=>{const cur=splitSkills(reqSkills.value);if(!cur.includes(b.dataset.skill))reqSkills.value=[...cur,b.dataset.skill].join(', ')})};
reqJdText.addEventListener('change',()=>{
  const val = reqJdText.value.trim();
  if(val && window.TSSDocumentParser?.handleJDText){
    window.TSSDocumentParser.handleJDText(val);
  } else {
    const p=parseJDText(reqJdText.value);
    if(!reqLocation.value&&p.location)reqLocation.value=p.location;
    if(!reqExperience.value&&p.experience)reqExperience.value=p.experience;
    if(!reqQualification.value&&p.qualification)reqQualification.value=p.qualification;
    if(!reqSkills.value&&p.skills.length)reqSkills.value=p.skills.join(', ');
  }
});
jdFile.onchange=async e=>{
  const f=e.target.files[0];
  if(!f)return;
  if(window.TSSDocumentParser?.handleJDFile){
    window.TSSDocumentParser.handleJDFile(f);
  } else if(f.type==='text/plain'||f.name.endsWith('.txt')){
    const txt=await f.text();
    reqJdText.value=txt;
    reqJdText.dispatchEvent(new Event('change'));
    toast('JD text extracted');
  }
};
saveRequirementBtn.onclick=()=>{if(!reqClient.value.trim()||!reqTitle.value.trim()){toast('Client and Job Title are required');return}const existing=reqId.value?db.requirements.find(x=>x.id===reqId.value):null;const id=existing?.id||`TSS${String(db.requirements.length+1).padStart(3,'0')}`;const manual=splitSkills(reqSkills.value),suggest=roleSkillSuggestions(reqTitle.value,reqIndustry.value),r={id,client:reqClient.value.trim(),title:reqTitle.value.trim(),location:reqLocation.value.trim(),experience:reqExperience.value.trim(),industry:reqIndustry.value.trim(),status:reqStatus.value,skills:manual.length?manual:suggest,preferred:splitSkills(reqPreferred.value),qualification:reqQualification.value.trim(),responsibilities:reqResponsibilities.value.trim(),jdText:reqJdText.value,aiSuggested:!manual.length};if(existing)Object.assign(existing,r);else db.requirements.push(r);db.activity.push({date:new Date().toISOString(),title:existing?'Requirement updated':'Requirement created',detail:`${r.client} — ${r.title}`});saveDB();dlg.close();toast(existing?'Requirement updated':'Requirement added');rematchRequirement(r);if(window.TSSGoogleSheets?.syncFullWorkspaceToMasterSheet){window.TSSGoogleSheets.syncFullWorkspaceToMasterSheet(false);}};
function rematchRequirement(r){const matches=db.candidates.map(c=>({c,s:scoreCandidate(c.resumeText||'',r,c).score})).filter(x=>x.s>=55);if(matches.length)toast(`${matches.length} existing CV match${matches.length>1?'es':''} found for ${r.title}`)}
window.db = db;
window.saveDB = saveDB;
window.scoreCandidate = scoreCandidate;
window.screeningLabel = screeningLabel;
window.showResult = showResult;
window.toast = toast;

resumeFile.onchange = async e => {
  const files = Array.from(e.target.files || []);
  if (!files.length) return;
  if (files.length > 1) {
    if (window.TSSBatchScreening?.processBatch) {
      window.TSSBatchScreening.processBatch(files);
    }
  } else {
    const f = files[0];
    if (window.TSSDocumentParser?.handleResumeFile) {
      window.TSSDocumentParser.handleResumeFile(f);
    } else if (f.type === 'text/plain' || f.name.endsWith('.txt')) {
      resumeText.value = await f.text();
      toast('Resume text loaded');
    }
  }
};
function scoreCandidate(text,r,c={}){const hay=norm(`${text} ${c.designation||''} ${c.location||''}`);const mandatory=r.skills||[],preferred=r.preferred||[];const matched=mandatory.filter(s=>hay.includes(norm(s).trim())||tokens(s).some(t=>hay.includes(t))),missing=mandatory.filter(s=>!matched.includes(s));const prefMatched=preferred.filter(s=>hay.includes(norm(s).trim())||tokens(s).some(t=>hay.includes(t)));const mandatoryPct=mandatory.length?matched.length/mandatory.length*100:70,prefPct=preferred.length?prefMatched.length/preferred.length*100:70;const reqYears=parseFloat((r.experience||'').match(/[\d.]+/)?.[0]||0),candYears=parseFloat(c.totalExperience||0),expPct=reqYears?Math.min(100,candYears/reqYears*100):75;const titleTokens=tokens(r.title),rolePct=titleTokens.length?titleTokens.filter(t=>hay.includes(t)).length/titleTokens.length*100:60;const locPct=!r.location||!c.location?70:(norm(c.location).includes(norm(r.location))||norm(r.location).includes(norm(c.location))?100:45);const respTokens=tokens(r.responsibilities).filter(t=>t.length>4),domainPct=respTokens.length?Math.min(100,respTokens.filter(t=>hay.includes(t)).length/Math.min(respTokens.length,12)*100):65;let score=Math.round(mandatoryPct*.38+prefPct*.1+expPct*.2+rolePct*.1+domainPct*.12+locPct*.1);score=Math.max(15,Math.min(98,score));return {score,matched,missing,prefMatched,mandatoryPct:Math.round(mandatoryPct),prefPct:Math.round(prefPct),expPct:Math.round(expPct),domainPct:Math.round(domainPct),locPct:Math.round(locPct)}}
function detectDuplicate(email,phone,text){return db.candidates.find(c=>(email&&c.email&&norm(c.email)===norm(email))||(phone&&c.phone&&c.phone.replace(/\D/g,'')===phone.replace(/\D/g,''))||(text&&c.resumeHash===simpleHash(text)))}function simpleHash(str){let h=0;for(let i=0;i<str.length;i++)h=((h<<5)-h)+str.charCodeAt(i)|0;return String(h)}
screenBtn.onclick=()=>{const r=db.requirements.find(x=>x.id===screenRequirement.value);if(!r){toast('Select requirement');return}const text=resumeText.value.trim();if(!candidateName.value.trim()||!text){toast('Candidate name and resume text are required');return}const curUser=window.TSSTeamIntelligence?.getCurrentUser?window.TSSTeamIntelligence.getCurrentUser():{name:'Recruiter',email:'recruiter@talent-stock.com',role:'recruiter'};const payload={name:candidateName.value.trim(),email:candidateEmail.value.trim(),phone:candidatePhone.value.trim(),totalExperience:candidateExp.value,location:candidateLocation.value.trim(),designation:candidateDesignation.value.trim(),noticePeriod:candidateNotice.value.trim(),currentCTC:candidateCTC.value.trim(),expectedCTC:candidateExpectedCTC.value.trim(),resumeText:text,resumeHash:simpleHash(text),uploadDate:new Date().toISOString(),uploadedBy:curUser.name,recruiterEmail:curUser.email};let c=detectDuplicate(payload.email,payload.phone,payload.resumeText);if(c){Object.assign(c,{...payload,id:c.id,uploadDate:c.uploadDate});toast('Duplicate candidate detected — existing profile reused')}else{c={id:`C${Date.now()}`,...payload};db.candidates.push(c)}const result=scoreCandidate(text,r,c);c.lastScreenedDate=new Date().toISOString();const rec=screeningLabel(result.score),s={id:`S${Date.now()}`,candidateId:c.id,candidateName:c.name,requirementId:r.id,requirementTitle:r.title,client:r.client,date:new Date().toISOString(),score:result.score,recommendation:rec,matched:result.matched,missing:result.missing,metrics:result,recruiterDecision:'Pending',notes:'',manualOverride:false,screenedBy:curUser.name,recruiterEmail:curUser.email,recruiterRole:curUser.role};db.screenings.push(s);db.activity.push({date:s.date,title:'Candidate screened',detail:`${c.name} — ${r.title} — ${result.score}/100 (by ${curUser.name})`});saveDB();showResult(s,c,r);toast('Screening complete');if(window.TSSGoogleSheets?.syncScreeningToSpreadsheet){window.TSSGoogleSheets.syncScreeningToSpreadsheet(s,c,r);}};
function showResult(s,c,r){screeningEmpty.classList.add('hidden');screeningResult.classList.remove('hidden');const m=s.metrics;screeningResult.innerHTML=`<div class="result-score"><div class="score-ring" style="--score:${s.score*3.6}deg"><strong>${s.score}</strong></div><div><span class="eyebrow">OVERALL MATCH</span><h3 style="margin:5px 0">${esc(c.name)}</h3>${statusBadge(s.recommendation)}<p style="color:var(--muted);font-size:12px">${esc(r.client)} · ${esc(r.title)}</p></div></div><div class="metric-grid"><div class="metric"><small>Mandatory Skill Match</small><strong>${m.mandatoryPct}%</strong></div><div class="metric"><small>Preferred Skill Match</small><strong>${m.prefPct}%</strong></div><div class="metric"><small>Experience Match</small><strong>${m.expPct}%</strong></div><div class="metric"><small>Domain Match</small><strong>${m.domainPct}%</strong></div><div class="metric"><small>Location Match</small><strong>${m.locPct}%</strong></div><div class="metric"><small>Recommendation</small><strong>${s.recommendation}</strong></div></div><div class="notes-box"><strong>Matching Skills</strong><div class="skill-cloud">${s.matched.map(x=>`<span class="skill">${esc(x)}</span>`).join('')||'<small>No exact keyword matches</small>'}</div></div><div class="notes-box"><strong>Missing / Unconfirmed Skills</strong><div class="skill-cloud">${s.missing.map(x=>`<span class="skill ai">${esc(x)}</span>`).join('')||'<small>No major mandatory gaps detected</small>'}</div></div><div class="notes-box"><strong>Clear Screening Explanation</strong><p style="color:var(--muted);font-size:13px">${explain(s,c,r)}</p></div><label>Recruiter Notes</label><textarea id="resultNotes" rows="3" placeholder="Add recruiter notes..."></textarea><div class="manual-actions"><button class="btn primary decision" data-d="Shortlisted">Shortlist</button><button class="btn ghost decision" data-d="Keep for Future">Keep for Future</button><button class="btn ghost decision" data-d="Request Updated Resume">Request Updated Resume</button><button class="btn ghost decision" data-d="Rejected">Reject</button><button class="btn ghost" id="approveAi">Approve AI Result</button><button class="btn ghost" id="editScore">Edit Score</button></div>`;document.querySelectorAll('.decision').forEach(b=>b.onclick=()=>updateDecision(s.id,b.dataset.d));approveAi.onclick=()=>updateDecision(s.id,'AI Result Approved');editScore.onclick=()=>{const n=prompt('Enter recruiter score (0-100)',s.score);if(n!==null&&!isNaN(n)){s.score=Math.max(0,Math.min(100,Number(n)));s.recommendation=screeningLabel(s.score);s.manualOverride=true;s.notes=resultNotes.value;saveDB();showResult(s,c,r);toast('Score manually updated')}}}
function explain(s,c,r){const strengths=[];if(s.metrics.mandatoryPct>=70)strengths.push('strong mandatory skill coverage');if(s.metrics.expPct>=90)strengths.push('experience meets the requirement');if(s.metrics.domainPct>=55)strengths.push('resume context overlaps with the role responsibilities');const concerns=[];if(s.missing.length)concerns.push(`${s.missing.length} mandatory skill(s) are not clearly evidenced`);if(s.metrics.locPct<60)concerns.push('location may need recruiter confirmation');return `The candidate scores ${s.score}/100 based on skills, experience, role relevance, domain context and location. ${strengths.length?'Strengths include '+strengths.join(', ')+'. ':''}${concerns.length?'Key concerns: '+concerns.join('; ')+'. ':''}This result does not reject candidates only on keyword differences; contextual and related terms are considered.`}
function updateDecision(id,d){const s=db.screenings.find(x=>x.id===id);s.recruiterDecision=d;s.notes=document.getElementById('resultNotes')?.value||s.notes;s.manualOverride=d!=='AI Result Approved';db.activity.push({date:new Date().toISOString(),title:'Recruiter decision',detail:`${d} — screening ${id}`});saveDB();toast(`Decision saved: ${d}`);if(window.TSSGoogleSheets?.syncDecisionUpdate){window.TSSGoogleSheets.syncDecisionUpdate(s.id,d,s.notes);}}
exportBtn.onclick=()=>{const headers=['Client Name','Job Title','Candidate Name','Email','Phone','Location','Total Experience','Relevant Experience','Current Designation','Match Score','Recommendation','Matching Skills','Missing Skills','Notice Period','Recruiter Decision','Recruiter Notes','Screening Date'];const rows=db.screenings.map(s=>{const c=db.candidates.find(x=>x.id===s.candidateId)||{},r=db.requirements.find(x=>x.id===s.requirementId)||{};return [r.client,r.title,c.name,c.email,c.phone,c.location,c.totalExperience,'',c.designation,s.score,s.recommendation,(s.matched||[]).join('; '),(s.missing||[]).join('; '),c.noticePeriod,s.recruiterDecision,s.notes,new Date(s.date).toLocaleString()]});const csv=[headers,...rows].map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`TSS_Screening_Export_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('Excel-compatible export downloaded')};
renderAll();