(function(){
  let pdfReady=null,mammothReady=null;
  function load(src){return new Promise((resolve,reject)=>{if([...document.scripts].some(s=>s.src===src))return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  async function parsePDF(file){if(!pdfReady)pdfReady=load('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js').then(()=>{window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'});await pdfReady;const data=new Uint8Array(await file.arrayBuffer());const pdf=await window.pdfjsLib.getDocument({data}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i);const c=await p.getTextContent();text+=c.items.map(x=>x.str).join(' ')+'\n'}return text.trim()}
  async function parseDOCX(file){if(!mammothReady)mammothReady=load('https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.8.0/mammoth.browser.min.js');await mammothReady;const r=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return(r.value||'').trim()}
  async function parse(file){const name=file.name.toLowerCase();if(file.type==='text/plain'||name.endsWith('.txt'))return(await file.text()).trim();if(file.type==='application/pdf'||name.endsWith('.pdf'))return parsePDF(file);if(name.endsWith('.docx'))return parseDOCX(file);throw new Error('This file type cannot be read in-browser. Please use PDF, DOCX or TXT.')}
  async function handleResume(file){if(!file)return;try{toast('Reading resume…');const text=await parse(file);if(!text)throw new Error('No readable text found');const box=document.getElementById('resumeText');if(box)box.value=text;toast('Resume extracted successfully')}catch(e){toast(e.message||'Resume parsing failed')}}
  async function handleJD(file){if(!file)return;try{toast('Reading JD…');const text=await parse(file);if(!text)throw new Error('No readable text found');const quick=document.getElementById('reqJdText');if(quick&&document.getElementById('requirementDialog')?.open){quick.value=text;quick.dispatchEvent(new Event('change'))}const select=document.getElementById('screenRequirement');const r=window.db?.requirements?.find(x=>x.id===select?.value);if(r){r.jdText=text;try{const p=parseJDText(text);if(p.location)r.location=p.location;if(p.experience)r.experience=p.experience;if(p.qualification)r.qualification=p.qualification;if(p.skills?.length)r.skills=[...new Set([...(r.skills||[]),...p.skills])]}catch{}try{saveDB()}catch{}try{renderOldSite()}catch{}}toast('JD extracted and saved')}catch(e){toast(e.message||'JD parsing failed')}}
  function wire(){const resume=document.getElementById('resumeFile');resume?.addEventListener('change',e=>handleResume(e.target.files?.[0]));const quick=document.getElementById('jdQuickFile');quick?.addEventListener('change',e=>handleJD(e.target.files?.[0]));const dialog=document.getElementById('jdFile');dialog?.addEventListener('change',e=>handleJD(e.target.files?.[0]))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();window.TSSDocumentParser={parse};
})();
