(function(){
  const $=id=>document.getElementById(id);
  const DB=()=>typeof db!=='undefined'?db:null;
  function parseDateTime(date,time){if(!date)return null;const m=String(time||'11:00 AM').match(/(\d{1,2}):(\d{2})\s*(AM|PM)?/i);let h=m?Number(m[1]):11,mm=m?Number(m[2]):0,ap=m?.[3]?.toUpperCase();if(ap==='PM'&&h<12)h+=12;if(ap==='AM'&&h===12)h=0;const d=new Date(`${date}T${String(h).padStart(2,'0')}:${String(mm).padStart(2,'0')}:00`);return isNaN(d)?null:d.toISOString()}
  async function persist(){const b=window.TSSBackend,store=DB();if(!b?.enabled||!store)return;const item=(store.interviews||[]).at(-1);if(!item||item.serverId)return;try{const user=await b.currentUser();if(!user)return;let cand=(store.candidates||[]).find(c=>String(c.name).toLowerCase()===String(item.candidate).toLowerCase());let candId=cand?.serverId||cand?.id;if(!candId||!String(candId).includes('-')){const created=await b.createOrUpdateCandidate({name:item.candidate||'Candidate',email:cand?.email||item.email||'',phone:cand?.phone||'',location:cand?.location||'',totalExperience:cand?.totalExperience||null,designation:cand?.designation||'',noticePeriod:cand?.noticePeriod||''});candId=created.candidate.id;cand={...(cand||{}),serverId:candId,email:created.candidate.email||cand?.email||item.email||''}}
    const req=(store.requirements||[]).find(r=>r.title===item.position&&r.client===item.client)||(store.requirements||[]).find(r=>r.id===$('screenRequirement')?.value);let reqId=req?.serverId;if(!reqId){const {data,error}=await b.client.from('requirements').select('id').eq('profile_key',req?.profileKey||req?.id).maybeSingle();if(error)throw error;reqId=data?.id}if(!reqId)throw new Error('Requirement not synced');const scheduled=parseDateTime(item.date,item.time);if(!scheduled)throw new Error('Invalid interview date/time');
    const payload={candidate_id:candId,requirement_id:reqId,scheduled_at:scheduled,status:'Scheduled',interview_type:item.mode||'Client Interview',interviewer:item.interviewer||null,location_or_link:item.locationOrLink||item.link||item.location||null,notes:item.notes||null,created_by:user.id,candidate_name_snapshot:item.candidate||cand?.name||'Candidate',candidate_email_snapshot:item.email||cand?.email||null,job_title_snapshot:item.position||req?.title||null,client_name_snapshot:item.client||req?.client||null,timezone:'Asia/Kolkata',candidate_response:'Pending',reminder_status:'Pending'};
    const {data,error}=await b.client.from('interviews').insert(payload).select().single();if(error)throw error;item.serverId=data.id;item.email=payload.candidate_email_snapshot;item.reminderStatus='Pending';item.candidateResponse='Pending';localStorage.setItem('tss_talent_buddy_v1',JSON.stringify(store));try{toast('Interview scheduled · confirmation + reminders queued')}catch{}}catch(e){console.warn(e);try{toast('Interview saved locally; backend sync failed: '+(e.message||e))}catch{}}}
  function wire(){$('scheduleInterview')?.addEventListener('click',()=>setTimeout(persist,250))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
