// TSS 42-profile master migration. Preserves candidate/screening/activity data.
(() => {
  const MASTER_VERSION = 'tss_master_profiles_42_v1';
  const master = [
    ['TSS001','ShipDelight Logistics','SaaS Sales','','2-5+ years in B2B SaaS sales','₹10 LPA',['B2B SaaS sales','enterprise solution selling','consultative selling','C-level stakeholder engagement','outbound lead generation','discovery and requirement analysis','product demonstrations','commercial proposal writing','negotiation and objection handling','CRM pipeline management','sales forecasting','contract closure']],
    ['TSS002','ShipDelight Logistics','Sales Manager - Sales','','7-12 years, including minimum 5 years in client acquisition','₹20 to 25 LPA',['B2B logistics sales','enterprise client acquisition','primary logistics','express logistics','transportation networks','sales pipeline management','commercial negotiation','logistics solution selling','proposal development','revenue forecasting','CRM governance','market development']],
    ['TSS003','ShipDelight Logistics','Sales Manager - Operations','','7-10 years in logistics operations, including at least 3 years in B2B express delivery operations','₹25 LPA',['B2B surface express operations','courier partner management','shipment lifecycle management','SLA and TAT governance','first mile operations','linehaul operations','last mile delivery','reverse logistics','operational escalation closure','logistics commercials','claims and penalty management','billing reconciliation','cost optimization','operational MIS and dashboards','KPI monitoring']],
    ['TSS004','ShipDelight Logistics','Key Account Manager','','','₹6 to 7 LPA',['key account management','client relationship management','account growth','upselling','cross-selling','negotiation','CRM','stakeholder management','revenue retention','business reviews']],
    ['TSS005','IntelTek','Senior Sales Manager','Pune HO / New Delhi / Ahmedabad','3-4 years in factory automation product and system sales; diploma route requires 3-5 years','₹6 to 10 LPA',['factory automation sales','industrial motors and drives','servo systems','PLCs and motion control','technical solution selling','product selection','BOM preparation','techno-commercial proposals','product demonstrations','lead generation','OEM account development','order negotiation and closure','MIS reporting','junior team guidance']],
    ['TSS006','IntelTek','Assistant Manager','Pune HO','6-7 years in factory automation sales; diploma route requires minimum 5-7 years','₹6 to 10 LPA',['factory automation sales management','sales team supervision','OEM and project business development','field sales planning','product presentations and demonstrations','competitive market analysis','sales performance monitoring','inventory planning','payment collection','MIS reporting','customer relationship management','product and sales training','CRM and Microsoft Office']],
    ['TSS007','IntelTek','Sales Engineer','Pune HO / Ahmedabad / New Delhi / Chennai / Bangalore','1-2 years in factory automation product and system sales; diploma route requires minimum 2 years','₹6 to 10 LPA',['factory automation sales','industrial motors and VFDs','servo motors and drives','PLCs','planetary gearboxes','linear motion products','lead generation','product presentations and demonstrations','product and solution selection','BOM preparation','techno-commercial proposals','order negotiation','payment recovery','sales MIS']],
    ['TSS008','IntelMac','Sales Manager','Regional headquarters, PAN India','10-15 years in CNC machine sales, including the last 3+ years at managerial or supervisory level leading a team','₹12 LPA',['CNC machine sales','CNC machine technical knowledge','machining applications','machining processes','quality parameters','techno-commercial discussions','proposal and quotation preparation','commercial negotiation','market intelligence','competitor analysis','sales forecasting','customer decision-maker engagement','payment collection','LC and order execution','people management','team leadership']],
    ['TSS009','InnovationM','Full Stack Developer (Angular + Node.js)','Mumbai','3-4 years','₹1,00,000 PM',['Angular','TypeScript','RxJS','Node.js','Fastify','REST API development','SQL databases','NoSQL databases','PostgreSQL','MongoDB','Redis caching','RabbitMQ','microservices architecture','Git','CI/CD pipelines']],
    ['TSS010','InnovationM','React Native Developer','Noida','4-5 years','₹1,00,000 PM',['React Native','Kotlin Multiplatform','Android development','iOS development','mobile application lifecycle','object-oriented programming','UI design principles','reusable mobile code','SQLite','web services','API integration','internationalization','localization','cross-platform application delivery','technical mentoring']],
    ['TSS011','Neosoft Technologies','C# .NET Core API / MS SQL / React / CI/CD / RabbitMQ','PAN India','5+ years','₹15 LPA',['C#','.NET Core','full stack development','REST API development','MS SQL Server','React.js','CI/CD pipelines','RabbitMQ']],
    ['TSS012','Neosoft Technologies','ASP.NET Core + Angular Developer','','','₹9.60 LPA',['ASP.NET Core','C#','Angular','TypeScript','REST APIs','Entity Framework Core','SQL','HTML','CSS','Git','unit testing','CI/CD']],
    ['TSS013','Neosoft Technologies','.NET Core + MSSQL / SQL Developer','Delhi / Bangalore','2+ years; senior opening 5+ years','₹12 LPA',['.NET Core','C#','ASP.NET Core','PostgreSQL','MS SQL Server','T-SQL','REST API development','Entity Framework Core','LINQ','SQL queries','stored procedures','query optimization','microservices','Git','debugging','performance optimization']],
    ['TSS014','Wipro','PostgreSQL Database Administrator','','5-10 years','₹17 to 20 LPA',['PostgreSQL 9.x+','database administration','high availability','disaster recovery','backup and recovery','replication','performance tuning','database patching','AWS Aurora PostgreSQL','shell scripting','capacity planning','ITIL incident and change management']],
    ['TSS015','Wipro','MSSQL Database Administrator','','6+ years','₹17 to 20 LPA',['Microsoft SQL Server','T-SQL','SQL Server installation and patching','backup and recovery','performance tuning','Always On availability groups','clustering','replication','log shipping','database security','Ansible automation','capacity planning']],
    ['TSS016','Wipro','Oracle DBA L2','Mumbai / Navi Mumbai; local Mumbai candidates only','4-6 years relevant experience','₹9 to 10 LPA',['Oracle Database 19c','Oracle RAC','RAC architecture','RAC installation and configuration','2-node and 3-node clusters','ASM','RMAN','backup and recovery','database patching','database upgrades','performance monitoring','GoldenGate','database security','migration','high availability','disaster recovery drills','failover testing','Linux']],
    ['TSS017','Wipro','Oracle DBA L3','Mumbai / Navi Mumbai; local Mumbai candidates only','6-8 years relevant experience','₹11 to 13 LPA',['Oracle Database 19c','advanced Oracle administration','Oracle RAC','RAC architecture and implementation','2-node and 3-node clusters','ASM','RMAN','backup and recovery','database patching','upgrades','performance tuning','GoldenGate architecture','database security','migration','high availability','disaster recovery drills','failover testing','Linux']],
    ['TSS018','Wipro','Linux Engineer L2','Mumbai / Navi Mumbai; local Mumbai candidates only','4-6 years relevant experience','₹11 to 13 LPA',['RHEL 8 and 9 administration','Linux installation and configuration','LVM','file systems','disk management','system performance tuning','Linux networking','DNS','routing','firewall','YUM','DNF','patch management','SELinux','SSH','NFS','FTP','Pacemaker cluster','Bash scripting','Ansible','incident management','ITIL']],
    ['TSS019','Wipro','Linux Engineer L3','','','₹17 LPA',['advanced Linux administration','Unix administration','AIX','enterprise infrastructure operations','BAU support','incident management','problem management','change management','server provisioning','patching and upgrades','performance tuning','high availability','security hardening','monitoring','Shell scripting','Ansible','disaster recovery','backup and restore','root cause analysis']],
    ['TSS020','Wipro','Network Engineer L3','','','₹23 LPA',['Cisco routing and switching','LAN and WAN','wireless networking','VLAN','STP/RSTP/MST','BGP','OSPF','MPLS','Cisco Nexus','firewalls','VPN','network monitoring','ITIL incident and change management','network troubleshooting']],
    ['TSS021','Tax Genie','Jr. Analyst','Andheri, Mumbai - client location at Marol Naka','Fresher / 0-1 year','₹22,000 in hand per month',['invoice processing','invoice verification','accounting entries','journal entries','vouchers','bookkeeping','Tally ERP9','Tally Prime','Microsoft Excel','Microsoft Word','GST documentation','email communication','record maintenance','data accuracy','typing speed 40 WPM']],
    ['TSS022','Tax Genie','PMO Analyst','','3-5 years','₹5.5 LPA',['Jira administration','project coordination','project tracking','Agile Scrum','stakeholder management','client communication','risk and issue tracking','UAT coordination','status reporting','documentation','Microsoft Excel','PowerPoint']],
    ['TSS023','Tax Genie','Business Analyst','Andheri, Mumbai','1-2 years','₹5.5 LPA',['requirement gathering','business process analysis','BRD','FRD','SRS','user stories','use cases','acceptance criteria','process mapping','Jira','UAT','functional testing','Microsoft Excel']],
    ['TSS024','Tax Genie','Sr. GST Analyst','','2-4 years','₹6.0 LPA',['GST compliance automation','e-Invoicing IRN','e-Way Bill','ASN automation','purchase order automation','DSC integration','SAP SD integration','REST APIs','Postman','SQL','UAT management','production support']],
    ['TSS025','Tax Genie','SAP ABAP Developer','','1-2 years','₹5.0 LPA',['SAP ABAP','RICEFW','ALV reports','Module Pool programming','SAP Data Dictionary','SmartForms','SAP Scripts','BAPI','RFC','IDoc','user exits','BADI','debugging and performance tuning']],
    ['TSS026','Upgrad Enterprise','Delivery Lead','Gurugram / Noida / Bangalore','15+ years','₹45.0 LPA',['portfolio delivery management','corporate L&D program delivery','Tech and Data programs','AI and analytics programs','digital transformation','client stakeholder management','SLA governance','program onboarding and closure','P&L ownership','revenue realization','cost optimization','margin management','account growth','team leadership','operational excellence','performance reporting']],
    ['TSS027','Upgrad Enterprise','Business Development Manager (Dubai)','Dubai / Abu Dhabi','3-5 years','Monthly CTC: 18,063 Dirhams; Annual CTC: 2,16,750 Dirhams',['business development','B2B enterprise sales','UAE account planning','SaaS sales','education solutions','L&D solution selling','new-logo acquisition','hunting and prospecting','cold calling','networking','client needs assessment','presentations and demos','negotiation and closing','CRM','sales pipeline management','market intelligence','revenue forecasting']],
    ['TSS028','Upgrad Enterprise','Key Account Manager','Mumbai','5+ years','₹25 LPA',['growth key account management','enterprise sales','new-logo acquisition','business development','hunting and prospecting','client relationship management','sales strategy','needs assessment','presentations and demos','negotiation and closing','account growth','stakeholder management','CRM','pipeline reporting','market intelligence']],
    ['TSS029','TLC Digitech','Sales Manager','Luxury hotels across metros and mini metros','3+ years','₹11.0 LPA',['front-end direct sales','membership sales','sales strategy','revenue growth','team management','lead generation','client relationship management','hospitality domain knowledge','CSAT management','renewal management','KPI reporting','staff training']],
    ['TSS030','TLC Digitech','Sales Associate','Luxury hotels across metros and mini metros','','₹5.0 LPA',['membership sales','customer engagement','in-person sales','hospitality domain knowledge','club ambassador team guidance','member enrolment','client relationship management','verbal English','presentation skills','customer service','hotel coordination','technology support']],
    ['TSS031','TLC Digitech','Cluster Manager','Bangalore','8-10 years','₹15.0 LPA',['multi-location membership operations','team leadership','direct sales','inbound and outbound sales','hospitality operations','budgeting','KPI and KRA management','CRM','data analysis and reporting','stakeholder management','customer satisfaction','staff retention']],
    ['TSS032','Venus Group of Companies','General Manager','Stratum @ Venus Grounds, Ahmedabad','15+ years','₹20.0 LPA',['F&B operations','banquet operations','multi-outlet hospitality management','P&L management','food cost control','event delivery','guest experience','vendor management','budgeting','SOP management','team leadership','marketing coordination']],
    ['TSS033','Venus Group of Companies','Sales Manager','','8+ years','₹15.0 LPA',['real estate sales','luxury residential sales','HNI and UHNI client management','lead generation','site visits','negotiation and closure','sales strategy','revenue targets','client relationship management','market research','sales documentation','Microsoft Office']],
    ['TSS034','Venus Group of Companies','Guest Relations Executive (GRE)','HO Office, Planet Venus, Venus Ground; additional restaurant openings at Nehru Nagar','','₹3.0 LPA',['guest relations','front office operations','customer service','professional communication','guest greeting and assistance','property visit scheduling','sales-team coordination','inquiry handling','complaint resolution','feedback management','records and reports','MS Office','administration','multitasking','event support']],
    ['TSS035','Upgrad','Senior Admission Counsellor - Team Lead','','','₹10.0 LPA',['admission counselling','team leadership','inside sales','education sales','lead conversion','CRM','target achievement','student counselling','follow-up','performance management','communication']],
    ['TSS036','Upgrad','Senior Admission Counsellor','Mumbai','2+ years EdTech sales, including at least 1 year in one company','₹8.0 LPA',['EdTech sales','admission profiling','lead qualification','inside sales','learner counselling','lead conversion','CRM management','auto dialer','objection handling','target achievement','verbal English','active listening']],
    ['TSS037','Liberty General Insurance','DVP','','','₹30.0 LPA',['insurance operations','business strategy','team leadership','P&L management','stakeholder management','risk management','regulatory compliance','performance management','business development','governance']],
    ['TSS038','Liberty General Insurance','Apprentice','Prabhadevi','Not required (Apprentice role)','₹14.76 LPA',['financial statement review','financial data extraction','basic financial adjustments','underwriting fundamentals','underwriting data preparation','underwriting system data entry','Microsoft Excel','data accuracy','attention to detail','communication','interpersonal skills','task prioritization']],
    ['TSS039','Neosoft Technologies','ASP.NET Core + Angular Developer','Delhi','5+ years','Up to ₹13 LPA',['ASP.NET Core','C#','Angular','TypeScript','REST APIs','Entity Framework Core','MS SQL Server','HTML and CSS','Git','Unit Testing','CI/CD']],
    ['TSS040','Neosoft Technologies','Senior Software Developer – ASP.NET Core','Juinagar (Mindspace), Navi Mumbai','5+ years','As per Company Standards / Best in Industry',['ASP.NET Core','C#','REST APIs','Entity Framework Core','MS SQL Server','LINQ','Software Design Patterns','Git','Unit Testing','Performance Optimisation','CI/CD']],
    ['TSS041','Neosoft Technologies','Database Developer (MS SQL & MySQL)','Delhi','5+ years','Up to ₹13 LPA',['MS SQL Server','MySQL','T-SQL','SQL Queries','Stored Procedures','Database Design','Query Optimisation','Indexes','Views and Functions','Data Migration','Performance Tuning']],
    ['TSS042','Neosoft Technologies','Microsoft BI Developer (MSBI Developer)','Gurgaon','5+ years','Up to ₹13 LPA',['Microsoft BI','SSIS','SSRS','SSAS','MS SQL Server','T-SQL','ETL','Data Warehousing','OLAP Cubes','Power BI','Performance Tuning']]
  ].map(([id,client,title,location,experience,salaryRange,skills]) => ({
    id, client, title, location: location || 'Not provided', experience: experience || 'Not provided',
    salaryRange, industry: /Wipro|Neosoft|InnovationM|React|Developer|DBA|Engineer L/.test(client + title) ? 'IT' : 'NON-IT',
    status:'Active', skills, preferred:[], qualification:'',
    responsibilities:`Screen candidates against the client-confirmed requirements for ${title}.`, jdText:'', aiSuggested:false,
    skillsSource:'client_confirmed'
  }));

  try {
    const marker = localStorage.getItem(MASTER_VERSION);
    if (!marker) {
      const extras = (db.requirements || []).filter(r => !/^TSS\d{3}$/.test(r.id) || Number(r.id.slice(3)) > 42);
      db.requirements = [...master, ...extras];
      db.activity = db.activity || [];
      db.activity.push({date:new Date().toISOString(), title:'42 active job profiles restored', detail:'Original TSS master requirement set loaded without deleting candidate or screening history.'});
      localStorage.setItem(MASTER_VERSION, new Date().toISOString());
      localStorage.setItem(DB_KEY, JSON.stringify(db));
      renderAll();
      if (typeof toast === 'function') toast('42 active TSS job profiles loaded');
    }
  } catch (e) {
    console.error('Master profile migration failed', e);
  }
})();
