(function(){
  const $=id=>document.getElementById(id);
  const esc2=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const domain='@talent-stock.com';
  const commonQuestions=[
    'What is your current CTC?',
    'What is your expected CTC?',
    'What is your current location and preferred work location?',
    'What is your notice period and earliest possible joining date?',
    'Please confirm your total experience and relevant experience for this role.',
    'What is your availability for the client interview?',
    'Are you comfortable with the stated work mode, location, shifts and travel requirements?'
  ];

  function nameFromEmail(email){const raw=(email||'Recruiter').split('@')[0].replace(/[._-]+/g,' ');return raw.replace(/\b\w/g,c=>c.toUpperCase())||'Recruiter'}
  function getSession(){try{return JSON.parse(localStorage.getItem('tss_user_session')||'null')}catch{return null}}
  function setSession(s){if(s)localStorage.setItem('tss_user_session',JSON.stringify(s));else localStorage.removeItem('tss_user_session')}
  function showWorkspace(session){$('loginGate')?.classList.add('hidden');$('workspace')?.classList.remove('hidden');const name=session?.name||nameFromEmail(session?.email);$('profileName').textContent=name;$('welcomeLine').textContent=`Welcome back, ${name}. Here's what's happening today.`;$('todoGreeting').textContent=`Hi ${name}! 👋`;$('todoModalGreeting').textContent=`Good evening, ${name}.`;renderOldSite()}
  function showLogin(){ $('workspace')?.classList.add('hidden');$('loginGate')?.classList.remove('hidden') }

  $('showLoginForm')?.addEventListener('click',()=>{$('showLoginForm').classList.add('hidden');$('loginForm').classList.remove('hidden');$('loginEmail').focus()});
  $('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const email=$('loginEmail').value.trim().toLowerCase(),password=$('loginPassword').value;const err=$('loginError');err.textContent='';if(!email.endsWith(domain)){err.textContent=`Access is restricted to ${domain} email addresses.`;return}try{if(window.TSSBackend?.enabled){await window.TSSBackend.signIn(email,password)}const s={email,name:nameFromEmail(email),role:'recruiter'};setSession(s);showWorkspace(s)}catch(ex){err.textContent=ex?.message||'Unable to sign in.'}});
  $('signOutBtn')?.addEventListener('click',async()=>{try{if(window.TSSBackend?.enabled)await window.TSSBackend.signOut()}catch{}setSession(null);showLogin()});

  function groupedRequirements(filter=''){const q=filter.toLowerCase();const grouped={};activeReqs().filter(r=>!q||`${r.id} ${r.client} ${r.title} ${r.location}`.toLowerCase().includes(q)).forEach(r=>(grouped[r.client]??=[]).push(r));return grouped}
  function renderClientTree(filter=''){const grouped=groupedRequirements(filter);$('clientRequirementTree').innerHTML=Object.entries(grouped).map(([client,rs])=>`<div class="client-group"><div class="client-group-title"><span>⌄</span>${esc2(client)}<b>${rs.length}</b></div>${rs.map(r=>`<div class="client-role" data-req="${r.id}"><strong><i>${r.id}</i>${esc2(r.title)}</strong><small>${esc2(r.location||'Not provided')}</small></div>`).join('')}</div>`).join('');document.querySelectorAll('.client-role').forEach(el=>el.onclick=()=>selectRequirement(el.dataset.req,true))}

  function selectRequirement(id,goScreen=false){const r=db.requirements.find(x=>x.id===id);if(!r)return;$('topRequirementSelect').value=id;$('screenRequirement').value=id;try{updateSelectedRequirement()}catch{}renderSelectedRequirement();if(goScreen){document.querySelector('.nav-item[data-view="screening"]')?.click();setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),20)}}
  function renderTopRequirements(){const active=activeReqs();$('topRequirementSelect').innerHTML=active.map(r=>`<option value="${r.id}">${esc2(r.title)} — ${esc2(r.client)}</option>`).join('');const selected=$('screenRequirement').value||active[0]?.id;if(selected&&active.some(r=>r.id===selected)){$('topRequirementSelect').value=selected;$('screenRequirement').value=selected}}

  function screeningForReq(id){return db.screenings.filter(s=>s.requirementId===id)}
  function matchAvg(id){const s=screeningForReq(id);return s.length?Math.round(s.reduce((a,b)=>a+(Number(b.score)||0),0)/s.length):0}
  function renderDashboardOld(){const active=activeReqs(),candidates=db.candidates||[],screenings=db.screenings||[],strong=screenings.filter(s=>s.recommendation==='Strong Match').length,review=screenings.filter(s=>s.recommendation==='Review Recommended').length,avg=screenings.length?Math.round(screenings.reduce((a,s)=>a+(Number(s.score)||0),0)/screenings.length):0,interviews=db.interviews||[];$('activeReqChip').textContent=`${active.length} active requirements`;$('worthReviewing').innerHTML=`${strong+review} candidates<br>worth reviewing`;$('qualityRing').style.setProperty('--quality',`${avg}%`);$('qualityRing').querySelector('b').textContent=`${avg}%`;
    const screened=new Set(screenings.map(s=>s.candidateId)).size,shortlisted=screenings.filter(s=>['Strong Match','Review Recommended'].includes(s.recommendation)).length,interviewCount=interviews.length,offers=screenings.filter(s=>/offer/i.test(s.recruiterDecision||'')).length;const pipeline=[['Sourced',candidates.length,100],['Screened',screened,84],['Shortlisted',shortlisted,68],['Interview',interviewCount,50],['Offer',offers,34]];$('pipelineVisual').innerHTML=pipeline.map(([l,n,w])=>`<div class="pipeline-row"><div class="pipeline-trapezoid" style="width:${w}%">${n}</div><span>${l}</span><b>${n}</b></div>`).join('');
    const todays=interviews.filter(i=>new Date(i.date).toDateString()===new Date().toDateString());$('todayInterviews').innerHTML=todays.length?todays.slice(0,5).map(i=>`<div class="question-row"><b>${esc2(i.time||'—')}</b>${esc2(i.candidate||'Candidate')} · ${esc2(i.position||'')}<span>${esc2(i.mode||'Interview')}</span></div>`).join(''):`<div class="empty-interviews"><div><b>▦</b><h4>No interviews scheduled today</h4><small>Open Interview Operations to schedule one.</small></div></div>`;
    const health=active.slice(-4).reverse();$('requirementHealth').innerHTML=`<div class="health-grid-live">${health.map(r=>{const a=matchAvg(r.id)||51;return `<div class="health-item"><span>▣ ${esc2(r.client)}</span><strong>${a}% <i>${a>=70?'On Track':'At Risk'}</i></strong><small>${screeningForReq(r.id).length} candidates · ${r.id}</small></div>`}).join('')}</div>`;
    $('recruiterWorkload').innerHTML=`<div class="workload-empty"><div class="workload-bar" data-count="${screenings.length}" data-name="${esc2(getSession()?.name||'Recruiter')}"></div></div>`;
    $('activeJobsTable').innerHTML=`<div style="overflow:auto"><table class="jobs-table"><thead><tr><th>Job Title</th><th>Client</th><th>Location</th><th>Candidates</th><th>Avg. Match</th><th>Status</th></tr></thead><tbody>${active.slice().reverse().slice(0,6).map(r=>`<tr class="job-open" data-req="${r.id}"><td><strong>${esc2(r.title)}</strong><small>${r.id}</small></td><td>${esc2(r.client)}</td><td>${esc2(r.location||'Not provided')}</td><td>${screeningForReq(r.id).length}</td><td><div class="match-mini">${matchAvg(r.id)}% <i style="--w:${matchAvg(r.id)}%"></i></div></td><td><span class="active-text">● Active</span></td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('.job-open').forEach(tr=>tr.onclick=()=>selectRequirement(tr.dataset.req,true));$('todoReviewCount').textContent=review;$('todoStrongCount').textContent=strong;$('todoInterviewCount').textContent=todays.length}

  function renderSelectedRequirement(){const r=db.requirements.find(x=>x.id===$('screenRequirement').value)||activeReqs()[0];if(!r)return;$('selectedRoleTitle').textContent=`${r.client} — ${r.title}`;$('selectedRoleMeta').textContent=`${r.id} · ${r.status}`;$('questionnaireId').textContent=`QNR${r.id.replace(/\D/g,'').padStart(4,'0')} · TSS RECRUITER SCREENING`;$('jobQuestionClient').textContent=r.client;$('candidateUploadSubtitle').textContent=`Screening against ${r.title} · ${r.client}`;
    $('selectedRequirementSummary').className='summary-box';$('selectedRequirementSummary').innerHTML=[['⌾','Location',r.location||'Not provided'],['▣','Experience',r.experience||'Not provided'],['▤','Salary',r.salaryRange||'Not provided'],['♧','Recruiter',r.recruiter||'Not provided'],['▱','Category',r.industry||'Not provided'],['▧','Interview Mode',r.interviewMode||'Not provided']].map(([ic,k,v])=>`<div class="summary-field"><span>${ic} &nbsp; ${k}</span><strong>${esc2(v)}</strong></div>`).join('');
    $('commonQuestions').innerHTML=commonQuestions.map((q,i)=>`<div class="question-row"><b>${i+1}</b>${esc2(q)}<span>COMMON</span></div>`).join('');const roleQs=(r.skills||[]).slice(0,8).map(s=>`Please describe your hands-on experience with ${s}.`);while(roleQs.length<8)roleQs.push(`Can you confirm your relevant experience for ${r.title}?`);$('jobSpecificQuestions').innerHTML=roleQs.map((q,i)=>`<div class="question-row"><b>${i+1}</b>${esc2(q)}<span>CLIENT JD</span></div>`).join('')}

  function renderInterviews(){const items=db.interviews||[];$('interviewBoard').innerHTML=items.length?`<table class="jobs-table"><thead><tr><th>Date</th><th>Time</th><th>Candidate</th><th>Position</th><th>Client</th><th>Mode</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc2(i.date)}</td><td>${esc2(i.time)}</td><td>${esc2(i.candidate)}</td><td>${esc2(i.position)}</td><td>${esc2(i.client)}</td><td>${esc2(i.mode)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">No interviews scheduled yet.</div>';$('navInterviewCount').textContent=items.length}

  function renderFilters(){const active=activeReqs(),clients=[...new Set(active.map(r=>r.client))].sort(),locs=[...new Set(active.map(r=>r.location).filter(Boolean))].sort();$('clientFilter').innerHTML='<option value="">All clients</option>'+clients.map(x=>`<option>${esc2(x)}</option>`).join('');$('locationFilter').innerHTML='<option value="">All locations</option>'+locs.map(x=>`<option>${esc2(x)}</option>`).join('')}
  function applyProfileFilter(){const q=$('jobProfileSearch').value.toLowerCase(),cl=$('clientFilter').value.toLowerCase(),lo=$('locationFilter').value.toLowerCase();document.querySelectorAll('#requirementCards .req-card').forEach(card=>{const txt=card.textContent.toLowerCase();card.style.display=(!q||txt.includes(q))&&(!cl||txt.includes(cl))&&(!lo||txt.includes(lo))?'block':'none'})}

  function renderOldSite(){renderTopRequirements();renderClientTree($('requirementSidebarSearch')?.value||'');renderDashboardOld();renderSelectedRequirement();renderInterviews();renderFilters();const active=activeReqs();$('navReqCount').textContent=active.length;$('clientReqCount').textContent=active.length;$('navCandidateCount').textContent=(db.candidates||[]).length;setTimeout(applyProfileFilter,0)}

  $('requirementSidebarSearch')?.addEventListener('input',e=>renderClientTree(e.target.value));$('topRequirementSelect')?.addEventListener('change',e=>selectRequirement(e.target.value,false));$('jobProfileSearch')?.addEventListener('input',applyProfileFilter);$('clientFilter')?.addEventListener('change',applyProfileFilter);$('locationFilter')?.addEventListener('change',applyProfileFilter);$('sidebarAddRequirement')?.addEventListener('click',()=>$('addRequirementBtn')?.click());$('askTodoBtn')?.addEventListener('click',()=>$('todoModal').classList.remove('hidden'));$('expandTodo')?.addEventListener('click',()=>$('todoModal').classList.remove('hidden'));$('closeTodo')?.addEventListener('click',()=>$('todoModal').classList.add('hidden'));$('todoModal')?.addEventListener('click',e=>{if(e.target===$('todoModal'))$('todoModal').classList.add('hidden')});document.querySelectorAll('[data-open-screening]').forEach(b=>b.addEventListener('click',()=>document.querySelector('.nav-item[data-view="screening"]')?.click()));document.querySelectorAll('.nav-shortcut').forEach(b=>b.addEventListener('click',()=>document.querySelector(`.nav-item[data-view="${b.dataset.target}"]`)?.click()));$('todoReport')?.addEventListener('click',()=>$('exportBtn')?.click());$('scheduleInterview')?.addEventListener('click',()=>{const r=db.requirements.find(x=>x.id===$('screenRequirement').value)||activeReqs()[0];const candidate=prompt('Candidate name');if(!candidate)return;const date=prompt('Interview date (YYYY-MM-DD)',new Date().toISOString().slice(0,10));const time=prompt('Interview time','11:00 AM');db.interviews=db.interviews||[];db.interviews.push({candidate,date,time,position:r?.title||'',client:r?.client||'',mode:'Client Interview'});saveDB();renderOldSite();toast('Interview scheduled')});
  $('pasteJdQuick')?.addEventListener('click',()=>{const t=prompt('Paste JD / requirement email text');if(!t)return;const r=db.requirements.find(x=>x.id===$('screenRequirement').value);if(r){r.jdText=t;const p=parseJDText(t);if(p.location)r.location=p.location;if(p.experience)r.experience=p.experience;if(p.qualification)r.qualification=p.qualification;if(p.skills?.length)r.skills=[...new Set([...(r.skills||[]),...p.skills])];saveDB();renderOldSite();toast('JD text saved to requirement')}});$('jdQuickFile')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const r=db.requirements.find(x=>x.id===$('screenRequirement').value);if(!r)return;if(f.type==='text/plain'||f.name.endsWith('.txt')){r.jdText=await f.text();const p=parseJDText(r.jdText);if(p.skills.length)r.skills=[...new Set([...(r.skills||[]),...p.skills])];saveDB();renderOldSite();toast('JD uploaded and read')}else toast('JD attached. PDF/DOC parsing activates when backend parser is configured.')});

  document.getElementById('nav')?.addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(!b)return;setTimeout(()=>{const titles={dashboard:'Recruitment Dashboard',requirements:'Job Profiles',screening:'Resume Screening Studio',candidates:'Candidate Records',history:'Candidate Screening History',interviews:'Interview Operations'};$('pageTitle').textContent=titles[b.dataset.view]||'Resume Intelligence';if(b.dataset.view==='screening')renderSelectedRequirement();if(b.dataset.view==='dashboard')renderDashboardOld()},0)});

  try{const coreSave=saveDB;saveDB=function(){coreSave();setTimeout(renderOldSite,0)}}catch{}
  window.renderOldSite=renderOldSite;
  setTimeout(()=>{const s=getSession();if(s&&s.email?.endsWith(domain))showWorkspace(s);else showLogin();renderOldSite()},120);
})();